// import { day1Date } from "../Constants";
export let agendaConsts = {
  1: [
    {
      startTime: "Jan 15, 2022 09:00:00",
      endTime: "Jan 15, 2022 09:30:00",
      category: "Opening",
      topic: "UNICON 2022",
      description: "Opening Welcome by NES",
      setting: "online",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 09:30:00",
      endTime: "Jan 15, 2022 10:00:00",
      category: "Keynote",
      topic: "Startup to IPO",
      description:
        "A Founder who has successfully gone for IPO to share his/her journey and tips on how to identify the right timing to do so",
      setting: "online",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 10:00:00",
      endTime: "Jan 15, 2022 10:30:00",
      category: "Fireside",
      topic: "Booming Industries - Robotics",
      description: "Robotics",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 10:30:00",
      endTime: "Jan 15, 2022 11:30:00",
      category: "Panel",
      topic: "First Steps",
      description:
        "Taking the first steps when starting a company, how to gauge whether the idea is good, what were some of the founders’ considerations, how to be brave when starting",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 11:30:00",
      endTime: "Jan 15, 2022 12:00:00",
      category: "Fireside",
      topic: "Booming Industries - SaaS",
      description: "Saas",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 12:00:00",
      endTime: "Jan 15, 2022 13:00:00",
      category: "Break",
      topic: "LUNCH",
    },
    {
      startTime: "Jan 15, 2022 13:00:00",
      endTime: "Jan 15, 2022 13:30:00",
      category: "Fireside",
      topic: "Post-Covid Startups/ SMEs",
      description: "Startups that were founded at the onset of COVID",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 13:30:00",
      endTime: "Jan 15, 2022 14:30:00",
      category: "Panel",
      topic: "ASEAN startup ecosystem",
      description:
        "Founders from neighboring countries to share their experiences and trends in their respective countries",
      setting: "online",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 14:30:00",
      endTime: "Jan 15, 2022 15:00:00",
      category: "Fireside",
      topic: "Women in Entrepreneurship",
      description:
        "A popular topic from last year UNICON, a panelist of women founders/CEOs",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 15:00:00",
      endTime: "Jan 15, 2022 16:00:00",
      category: "Panel",
      topic: "Startups vs Corporates",
      description:
        "Experiences from founders that have worked in both, started working in a corporate setting as a fresh graduate then starting their own company afterwards",
      setting: "online",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 16:00:00",
      endTime: "Jan 15, 2022 17:00:00",
      category: "Panel",
      topic: "Innovation and new technologies",
      description:
        "Exploring DeepTech and learning from founders who are innovating in new technologies.",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 17:00:00",
      endTime: "Jan 15, 2022 17:30:00",
      category: "Fireside",
      topic: "Student Entrepreneurs",
      description:
        "How they managed their startup while still being a student, how to be disciplined and be able to manage their time well between managing their startup and academics",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 17:30:00",
      endTime: "Jan 15, 2022 18:30:00",
      category: "Panel",
      topic: "Seed to Unicorn",
      description:
        "Potentially a panelist of founders, early employees or high-ranking employees from unicorn startups, how they managed to reach the unicorn status",
      setting: "online",
      venue: "zoom link (tbc)",
    },
  ],
  2: [
    {
      startTime: "Jan 15, 2022 09:30:00",
      endTime: "Jan 15, 2022 10:00:00",
      category: "Opening by NES",
      topic: "UNICON 2022",
      description: "Opening Welcome by NES",
      setting: "online",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 10:00:00",
      endTime: "Jan 15, 2022 11:00:00",
      category: "Panel",
      topic: "Securing Funding",
      description:
        "A panel of VC partners, what do they look for in early stage startups, important points to note when pitching",
      setting: "online",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 10:00:00",
      endTime: "Jan 15, 2022 10:30:00",
      category: "Fireside",
      topic: "Booming Industries - FinTech",
      description: "FinTech",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 11:30:00",
      endTime: "Jan 15, 2022 13:00:00",
      category: "TigerLaunch",
    //   category: "Tigerlaunch pitching",
      topic: "TigerLaunch Pitching #1",
      description:
        "Part 1 of the pitching (First set of Teams out of total 15 Teams)",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 13:00:00",
      endTime: "Jan 15, 2022 14:00:00",
      category: "Break",
      topic: "LUNCH",
    },
    {
      startTime: "Jan 15, 2022 14:00:00",
      endTime: "Jan 15, 2022 15:00:00",
      category: "TigerLaunch",
    //   category: "Tigerlaunch pitching",
      topic: "TigerLaunch Pitching #2",
      description:
        "Part 2 of the pitching (Second set of Teams out of total 15 Teams)",
      setting: "physical",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 15:00:00",
      endTime: "Jan 15, 2022 16:00:00",
      category: "TigerLaunch",
    //   category: "Tigerlaunch Judging and panel",
      topic: "Zero to One",
      description:
        "How founders learnt from their mistakes, lessons from failures in companies/business ideas they executed prior to their successful startup, how to apply the lessons learnt onto their next startup",
      setting: "online",
      venue: "zoom link (tbc)",
    },
    {
      startTime: "Jan 15, 2022 16:00:00",
      endTime: "Jan 15, 2022 16:30:00",
      category: "TigerLaunch",
      topic: "TigerLaunch results & UNICON Closing",
      setting: "physical",
      venue: "zoom link (tbc)",
    }
  ],
};
